# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import files_rc1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 550)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 550))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 550))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Side_menu = QtWidgets.QFrame(self.centralwidget)
        self.Side_menu.setMinimumSize(QtCore.QSize(190, 0))
        self.Side_menu.setMaximumSize(QtCore.QSize(190, 16777215))
        self.Side_menu.setStyleSheet("background-color: rgb(51, 66, 87);\n")
        self.Side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Side_menu.setObjectName("Side_menu")
        self.Buttons = QtWidgets.QWidget(self.Side_menu)
        self.Buttons.setGeometry(QtCore.QRect(0, 220, 190, 321))
        self.Buttons.setObjectName("Buttons")
        self.AddWidget = QtWidgets.QWidget(self.Buttons)
        self.AddWidget.setGeometry(QtCore.QRect(-1, 0, 190, 80))
        self.AddWidget.setObjectName("AddWidget")
        self.AddButton = QtWidgets.QPushButton(self.AddWidget)
        self.AddButton.setGeometry(QtCore.QRect(0, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddButton.setFont(font)
        self.AddButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddButton.setStyleSheet("QPushButton{\n"
"color: rgb(210, 210, 210);\n"
"padding: 20px;\n"
"background-color: transparent;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43, 58, 79);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 5px transparent\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"background-color: rgb(41, 56, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 7px solid #0DDF90\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddButton.setIcon(icon)
        self.AddButton.setIconSize(QtCore.QSize(48, 48))
        self.AddButton.setShortcut("")
        self.AddButton.setCheckable(False)
        self.AddButton.setAutoRepeat(False)
        self.AddButton.setObjectName("AddButton")
        self.SearchWidget = QtWidgets.QWidget(self.Buttons)
        self.SearchWidget.setGeometry(QtCore.QRect(0, 80, 190, 80))
        self.SearchWidget.setObjectName("SearchWidget")
        self.SearchButton = QtWidgets.QPushButton(self.SearchWidget)
        self.SearchButton.setGeometry(QtCore.QRect(0, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SearchButton.setFont(font)
        self.SearchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SearchButton.setStyleSheet("QPushButton{\n"
"color: rgb(210, 210, 210);\n"
"padding: 20px;\n"
"background-color: transparent;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43, 58, 79);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 5px transparent\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"background-color: rgb(41, 56, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 7px solid #0DDF90\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon1)
        self.SearchButton.setIconSize(QtCore.QSize(48, 48))
        self.SearchButton.setCheckable(False)
        self.SearchButton.setAutoRepeat(False)
        self.SearchButton.setObjectName("SearchButton")
        self.DeleteWidget = QtWidgets.QWidget(self.Buttons)
        self.DeleteWidget.setGeometry(QtCore.QRect(0, 160, 190, 80))
        self.DeleteWidget.setObjectName("DeleteWidget")
        self.DeleteButton = QtWidgets.QPushButton(self.DeleteWidget)
        self.DeleteButton.setGeometry(QtCore.QRect(0, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DeleteButton.setStyleSheet("QPushButton{\n"
"color: rgb(210, 210, 210);\n"
"padding: 20px;\n"
"background-color: transparent;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43, 58, 79);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 5px transparent\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"background-color: rgb(41, 56, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 7px solid #0DDF90\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteButton.setIcon(icon2)
        self.DeleteButton.setIconSize(QtCore.QSize(48, 48))
        self.DeleteButton.setCheckable(False)
        self.DeleteButton.setAutoRepeat(False)
        self.DeleteButton.setObjectName("DeleteButton")
        self.InfoWidget = QtWidgets.QWidget(self.Buttons)
        self.InfoWidget.setGeometry(QtCore.QRect(0, 240, 190, 80))
        self.InfoWidget.setObjectName("InfoWidget")
        self.InfoButton = QtWidgets.QPushButton(self.InfoWidget)
        self.InfoButton.setGeometry(QtCore.QRect(0, 0, 190, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.InfoButton.setFont(font)
        self.InfoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InfoButton.setStyleSheet("QPushButton{\n"
"color: rgb(210, 210, 210);\n"
"padding: 20px;\n"
"background-color: transparent;\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(43, 58, 79);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 5px transparent\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"background-color: rgb(41, 56, 77);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"border-left: 7px solid #0DDF90\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Infos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InfoButton.setIcon(icon3)
        self.InfoButton.setIconSize(QtCore.QSize(48, 48))
        self.InfoButton.setCheckable(False)
        self.InfoButton.setAutoRepeat(False)
        self.InfoButton.setObjectName("InfoButton")
        self.WhiteBar = QtWidgets.QFrame(self.Side_menu)
        self.WhiteBar.setGeometry(QtCore.QRect(20, 180, 150, 3))
        self.WhiteBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WhiteBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WhiteBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WhiteBar.setObjectName("WhiteBar")
        self.exitBttn = QtWidgets.QPushButton(self.Side_menu)
        self.exitBttn.setGeometry(QtCore.QRect(45, 30, 100, 100))
        self.exitBttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBttn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/Icons/exit_normal.png);\n"
"    background: transparent;\n"
"    background-repeat: no-repeat;\n"
"    width: 100px;\n"
"    height: 100px;\n"
"    border-radius: 60px;\n"
"    border: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/Icons/exit_hover.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"")
        self.exitBttn.setText("")
        self.exitBttn.setAutoDefault(False)
        self.exitBttn.setObjectName("exitBttn")
        self.WhiteBorder = QtWidgets.QFrame(self.Side_menu)
        self.WhiteBorder.setGeometry(QtCore.QRect(35, 20, 120, 120))
        self.WhiteBorder.setStyleSheet("background: transparent;\n"
"border-radius: 60px;\n"
"border: 6px solid rgb(255, 255, 255);")
        self.WhiteBorder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WhiteBorder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WhiteBorder.setObjectName("WhiteBorder")
        self.WhiteBorder.raise_()
        self.Buttons.raise_()
        self.WhiteBar.raise_()
        self.exitBttn.raise_()
        self.horizontalLayout.addWidget(self.Side_menu)
        self.TotalWhiteArea = QtWidgets.QFrame(self.centralwidget)
        self.TotalWhiteArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"")
        self.TotalWhiteArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TotalWhiteArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TotalWhiteArea.setObjectName("TotalWhiteArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TotalWhiteArea)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.WSD = QtWidgets.QFrame(self.TotalWhiteArea)
        self.WSD.setMaximumSize(QtCore.QSize(12, 16777215))
        self.WSD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WSD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.WSD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WSD.setObjectName("WSD")
        self.horizontalLayout_2.addWidget(self.WSD)
        self.BSD = QtWidgets.QFrame(self.TotalWhiteArea)
        self.BSD.setMaximumSize(QtCore.QSize(12, 16777215))
        self.BSD.setStyleSheet("background-color: rgb(51, 66, 87);")
        self.BSD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BSD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BSD.setObjectName("BSD")
        self.horizontalLayout_2.addWidget(self.BSD)
        self.WorkSpace = QtWidgets.QFrame(self.TotalWhiteArea)
        self.WorkSpace.setMaximumSize(QtCore.QSize(800, 16777215))
        self.WorkSpace.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.WorkSpace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WorkSpace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WorkSpace.setObjectName("WorkSpace")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.WorkSpace)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.WorkSpace)
        self.Header.setMaximumSize(QtCore.QSize(16777215, 55))
        self.Header.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-top-right-radius: 30px;\n"
"border-bottom-right-radius: 30px;")
        self.Header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.BlueBar = QtWidgets.QWidget(self.Header)
        self.BlueBar.setGeometry(QtCore.QRect(40, 43, 750, 12))
        self.BlueBar.setStyleSheet("\n"
"background-color: rgb(60, 76, 97);")
        self.BlueBar.setObjectName("BlueBar")
        self.BlueBar_2 = QtWidgets.QWidget(self.BlueBar)
        self.BlueBar_2.setGeometry(QtCore.QRect(0, 0, 750, 12))
        self.BlueBar_2.setStyleSheet("background-color: rgb(60, 76, 97);\n")
        self.BlueBar_2.setObjectName("BlueBar_2")
        self.BlueCircle = QtWidgets.QLabel(self.Header)
        self.BlueCircle.setGeometry(QtCore.QRect(675, 10, 24, 24))
        self.BlueCircle.setText("")
        self.BlueCircle.setPixmap(QtGui.QPixmap(":/Icons/BlueCircle.png"))
        self.BlueCircle.setScaledContents(True)
        self.BlueCircle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.BlueCircle.setObjectName("BlueCircle")
        self.WhiteCircle = QtWidgets.QLabel(self.Header)
        self.WhiteCircle.setGeometry(QtCore.QRect(710, 10, 24, 24))
        self.WhiteCircle.setText("")
        self.WhiteCircle.setPixmap(QtGui.QPixmap(":/Icons/WhiteCircleV2.png"))
        self.WhiteCircle.setScaledContents(True)
        self.WhiteCircle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.WhiteCircle.setObjectName("WhiteCircle")
        self.BlackCircle = QtWidgets.QLabel(self.Header)
        self.BlackCircle.setGeometry(QtCore.QRect(745, 10, 24, 24))
        self.BlackCircle.setText("")
        self.BlackCircle.setPixmap(QtGui.QPixmap(":/Icons/BlackCircle.png"))
        self.BlackCircle.setScaledContents(True)
        self.BlackCircle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.BlackCircle.setObjectName("BlackCircle")
        self.popup = QtWidgets.QFrame(self.Header)
        self.popup.setGeometry(QtCore.QRect(39, 5, 610, 30))
        self.popup.setStyleSheet("background-color: #0DDF90;\n"
"border-radius: 11px;")
        self.popup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.popup.setObjectName("popup")
        self.popupclosebtn = QtWidgets.QPushButton(self.popup)
        self.popupclosebtn.setGeometry(QtCore.QRect(580, 5, 20, 20))
        self.popupclosebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.popupclosebtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/deleteicon4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.popupclosebtn.setIcon(icon4)
        self.popupclosebtn.setIconSize(QtCore.QSize(20, 20))
        self.popupclosebtn.setObjectName("popupclosebtn")
        self.textpopup = QtWidgets.QLabel(self.popup)
        self.textpopup.setGeometry(QtCore.QRect(130, 6, 350, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.textpopup.setFont(font)
        self.textpopup.setStyleSheet("color:rgb(255, 255, 255)")
        self.textpopup.setAlignment(QtCore.Qt.AlignCenter)
        self.textpopup.setObjectName("textpopup")
        self.verticalLayout_2.addWidget(self.Header)
        self.WorkSpace_2 = QtWidgets.QWidget(self.WorkSpace)
        self.WorkSpace_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WorkSpace_2.setObjectName("WorkSpace_2")
        self.pages = QtWidgets.QStackedWidget(self.WorkSpace_2)
        self.pages.setGeometry(QtCore.QRect(0, 0, 791, 401))
        self.pages.setObjectName("pages")
        self.Homepage = QtWidgets.QWidget()
        self.Homepage.setObjectName("Homepage")
        self.BlueBar_3 = QtWidgets.QWidget(self.Homepage)
        self.BlueBar_3.setGeometry(QtCore.QRect(250, 100, 250, 5))
        self.BlueBar_3.setStyleSheet("background-color: rgb(60, 76, 97);\n"
"\n"
"")
        self.BlueBar_3.setObjectName("BlueBar_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Homepage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(250, 40, 251, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ConjuntoPI = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ConjuntoPI.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ConjuntoPI.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoPI.setSpacing(8)
        self.ConjuntoPI.setObjectName("ConjuntoPI")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoPI.addItem(spacerItem)
        self.icon_topIP = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.icon_topIP.setMaximumSize(QtCore.QSize(43, 43))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        self.icon_topIP.setFont(font)
        self.icon_topIP.setText("")
        self.icon_topIP.setPixmap(QtGui.QPixmap(":/Icons/home.png"))
        self.icon_topIP.setScaledContents(True)
        self.icon_topIP.setObjectName("icon_topIP")
        self.ConjuntoPI.addWidget(self.icon_topIP)
        self.text_topIP = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.text_topIP.setMaximumSize(QtCore.QSize(220, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_topIP.setFont(font)
        self.text_topIP.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.text_topIP.setAlignment(QtCore.Qt.AlignCenter)
        self.text_topIP.setObjectName("text_topIP")
        self.ConjuntoPI.addWidget(self.text_topIP)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoPI.addItem(spacerItem1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Homepage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 160, 402, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ConjuntoTextoPI = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ConjuntoTextoPI.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoTextoPI.setObjectName("ConjuntoTextoPI")
        self.text1PI = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text1PI.setFont(font)
        self.text1PI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text1PI.setObjectName("text1PI")
        self.ConjuntoTextoPI.addWidget(self.text1PI)
        self.text2PI = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text2PI.setFont(font)
        self.text2PI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text2PI.setObjectName("text2PI")
        self.ConjuntoTextoPI.addWidget(self.text2PI)
        self.text3PI = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text3PI.setFont(font)
        self.text3PI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text3PI.setObjectName("text3PI")
        self.ConjuntoTextoPI.addWidget(self.text3PI)
        self.text4PI = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text4PI.setFont(font)
        self.text4PI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text4PI.setObjectName("text4PI")
        self.ConjuntoTextoPI.addWidget(self.text4PI)
        self.BSD_2 = QtWidgets.QFrame(self.Homepage)
        self.BSD_2.setGeometry(QtCore.QRect(190, 160, 5, 160))
        self.BSD_2.setMaximumSize(QtCore.QSize(12, 16777215))
        self.BSD_2.setStyleSheet("background-color: rgb(51, 66, 87);")
        self.BSD_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BSD_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BSD_2.setObjectName("BSD_2")
        self.DBIcon = QtWidgets.QLabel(self.Homepage)
        self.DBIcon.setGeometry(QtCore.QRect(100, 170, 64, 64))
        self.DBIcon.setText("")
        self.DBIcon.setPixmap(QtGui.QPixmap(":/Icons/DB.png"))
        self.DBIcon.setScaledContents(True)
        self.DBIcon.setObjectName("DBIcon")
        self.ExcelIcon = QtWidgets.QLabel(self.Homepage)
        self.ExcelIcon.setGeometry(QtCore.QRect(100, 250, 64, 64))
        self.ExcelIcon.setText("")
        self.ExcelIcon.setPixmap(QtGui.QPixmap(":/Icons/1bdb8ac897512116cbac58ffe7560d82.png"))
        self.ExcelIcon.setScaledContents(True)
        self.ExcelIcon.setObjectName("ExcelIcon")
        self.horizontalLayoutWidget.raise_()
        self.BlueBar_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.BSD_2.raise_()
        self.DBIcon.raise_()
        self.ExcelIcon.raise_()
        self.pages.addWidget(self.Homepage)
        self.Add1 = QtWidgets.QWidget()
        self.Add1.setObjectName("Add1")
        self.BlueBar_4 = QtWidgets.QWidget(self.Add1)
        self.BlueBar_4.setGeometry(QtCore.QRect(250, 100, 250, 5))
        self.BlueBar_4.setStyleSheet("background-color: rgb(60, 76, 97);\n"
"\n"
"")
        self.BlueBar_4.setObjectName("BlueBar_4")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Add1)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(250, 40, 251, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.ConjuntoAd = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.ConjuntoAd.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ConjuntoAd.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoAd.setSpacing(8)
        self.ConjuntoAd.setObjectName("ConjuntoAd")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoAd.addItem(spacerItem2)
        self.IconTopAd = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.IconTopAd.setMaximumSize(QtCore.QSize(43, 43))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        self.IconTopAd.setFont(font)
        self.IconTopAd.setText("")
        self.IconTopAd.setPixmap(QtGui.QPixmap(":/Icons/free-user-icon-3296-thumb.png"))
        self.IconTopAd.setScaledContents(True)
        self.IconTopAd.setObjectName("IconTopAd")
        self.ConjuntoAd.addWidget(self.IconTopAd)
        self.text_TopAd = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.text_TopAd.setMaximumSize(QtCore.QSize(220, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_TopAd.setFont(font)
        self.text_TopAd.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.text_TopAd.setAlignment(QtCore.Qt.AlignCenter)
        self.text_TopAd.setObjectName("text_TopAd")
        self.ConjuntoAd.addWidget(self.text_TopAd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoAd.addItem(spacerItem3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Add1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 150, 441, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ConjuntoTextoAD = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ConjuntoTextoAD.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoTextoAD.setObjectName("ConjuntoTextoAD")
        self.text1Ad = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text1Ad.setFont(font)
        self.text1Ad.setStyleSheet("text-align: left;")
        self.text1Ad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text1Ad.setObjectName("text1Ad")
        self.ConjuntoTextoAD.addWidget(self.text1Ad)
        self.text2Ad = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text2Ad.setFont(font)
        self.text2Ad.setStyleSheet("text-align: center;\n"
"")
        self.text2Ad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text2Ad.setObjectName("text2Ad")
        self.ConjuntoTextoAD.addWidget(self.text2Ad)
        self.text3Ad = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text3Ad.setFont(font)
        self.text3Ad.setStyleSheet("QLabel{\n"
"text-align: center\n"
"}")
        self.text3Ad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text3Ad.setObjectName("text3Ad")
        self.ConjuntoTextoAD.addWidget(self.text3Ad)
        self.BSD_4 = QtWidgets.QFrame(self.Add1)
        self.BSD_4.setGeometry(QtCore.QRect(280, 150, 5, 110))
        self.BSD_4.setMaximumSize(QtCore.QSize(12, 16777215))
        self.BSD_4.setStyleSheet("background-color: rgb(51, 66, 87);")
        self.BSD_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BSD_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BSD_4.setObjectName("BSD_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Add1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 150, 241, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.ConjuntoInputAD = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.ConjuntoInputAD.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoInputAD.setObjectName("ConjuntoInputAD")
        self.ConjuntoAlunoAD = QtWidgets.QHBoxLayout()
        self.ConjuntoAlunoAD.setObjectName("ConjuntoAlunoAD")
        self.AlunoIconAD = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.AlunoIconAD.setMaximumSize(QtCore.QSize(32, 32))
        self.AlunoIconAD.setText("")
        self.AlunoIconAD.setPixmap(QtGui.QPixmap(":/Icons/free-user-icon-3296-thumb.png"))
        self.AlunoIconAD.setScaledContents(True)
        self.AlunoIconAD.setObjectName("AlunoIconAD")
        self.ConjuntoAlunoAD.addWidget(self.AlunoIconAD)
        self.InputNomeAlunoAD = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.InputNomeAlunoAD.setMinimumSize(QtCore.QSize(190, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.InputNomeAlunoAD.setFont(font)
        self.InputNomeAlunoAD.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(210, 210, 210);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(150, 150, 150);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(51, 66, 87);\n"
"color: rgb(51, 66, 87);\n"
"}")
        self.InputNomeAlunoAD.setMaxLength(100)
        self.InputNomeAlunoAD.setObjectName("InputNomeAlunoAD")
        self.ConjuntoAlunoAD.addWidget(self.InputNomeAlunoAD)
        self.ConjuntoInputAD.addLayout(self.ConjuntoAlunoAD)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ConjuntoInputAD.addItem(spacerItem4)
        self.ConjuntoCursoAD = QtWidgets.QHBoxLayout()
        self.ConjuntoCursoAD.setObjectName("ConjuntoCursoAD")
        self.CursoIconAD = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.CursoIconAD.setMaximumSize(QtCore.QSize(32, 32))
        self.CursoIconAD.setText("")
        self.CursoIconAD.setPixmap(QtGui.QPixmap(":/Icons/beca icon.png"))
        self.CursoIconAD.setScaledContents(True)
        self.CursoIconAD.setObjectName("CursoIconAD")
        self.ConjuntoCursoAD.addWidget(self.CursoIconAD)
        self.InputCursoAD = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.InputCursoAD.setMinimumSize(QtCore.QSize(190, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.InputCursoAD.setFont(font)
        self.InputCursoAD.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(210, 210, 210);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(150, 150, 150);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(51, 66, 87);\n"
"}")
        self.InputCursoAD.setText("")
        self.InputCursoAD.setMaxLength(35)
        self.InputCursoAD.setObjectName("InputCursoAD")
        self.ConjuntoCursoAD.addWidget(self.InputCursoAD)
        self.ConjuntoInputAD.addLayout(self.ConjuntoCursoAD)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ConjuntoInputAD.addItem(spacerItem5)
        self.ConjuntoNumArmAD = QtWidgets.QHBoxLayout()
        self.ConjuntoNumArmAD.setObjectName("ConjuntoNumArmAD")
        self.ArmarioIconAD = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.ArmarioIconAD.setMaximumSize(QtCore.QSize(32, 32))
        self.ArmarioIconAD.setText("")
        self.ArmarioIconAD.setPixmap(QtGui.QPixmap(":/Icons/locker.png"))
        self.ArmarioIconAD.setScaledContents(True)
        self.ArmarioIconAD.setObjectName("ArmarioIconAD")
        self.ConjuntoNumArmAD.addWidget(self.ArmarioIconAD)
        self.InputArmarioAD = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.InputArmarioAD.setMinimumSize(QtCore.QSize(190, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.InputArmarioAD.setFont(font)
        self.InputArmarioAD.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(210, 210, 210);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(150, 150, 150);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(51, 66, 87);\n"
"}")
        self.InputArmarioAD.setMaxLength(8)
        self.InputArmarioAD.setObjectName("InputArmarioAD")
        self.ConjuntoNumArmAD.addWidget(self.InputArmarioAD)
        self.ConjuntoInputAD.addLayout(self.ConjuntoNumArmAD)
        self.RegistrarBttn = QtWidgets.QPushButton(self.Add1)
        self.RegistrarBttn.setGeometry(QtCore.QRect(425, 310, 240, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.RegistrarBttn.setFont(font)
        self.RegistrarBttn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(10, 10, 10);\n"
"border: 2px solid rgb(210, 210, 210);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(250, 250, 250);\n"
"color: rgb(10, 10, 10);\n"
"border: 2px solid rgb(160, 160, 160);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #0DDF90;\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(155, 155, 155);\n"
"border-radius: 20px;\n"
"}")
        self.RegistrarBttn.setObjectName("RegistrarBttn")
        self.Icon_Registrar_Button = QtWidgets.QLabel(self.Add1)
        self.Icon_Registrar_Button.setGeometry(QtCore.QRect(355, 310, 55, 55))
        self.Icon_Registrar_Button.setText("")
        self.Icon_Registrar_Button.setPixmap(QtGui.QPixmap(":/Icons/adduser.png"))
        self.Icon_Registrar_Button.setScaledContents(True)
        self.Icon_Registrar_Button.setObjectName("Icon_Registrar_Button")
        self.horizontalLayoutWidget_3.raise_()
        self.BlueBar_4.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.BSD_4.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.RegistrarBttn.raise_()
        self.Icon_Registrar_Button.raise_()
        self.pages.addWidget(self.Add1)
        self.Search1 = QtWidgets.QWidget()
        self.Search1.setObjectName("Search1")
        self.BlueBar_5 = QtWidgets.QWidget(self.Search1)
        self.BlueBar_5.setGeometry(QtCore.QRect(250, 100, 250, 5))
        self.BlueBar_5.setStyleSheet("background-color: rgb(60, 76, 97);\n"
"\n"
"")
        self.BlueBar_5.setObjectName("BlueBar_5")
        self.TabelaBuscar = QtWidgets.QTableWidget(self.Search1)
        self.TabelaBuscar.setGeometry(QtCore.QRect(70, 130, 650, 261))
        self.TabelaBuscar.setStyleSheet("QHeaderView::section{\n"
"font: 10pt \"Seoge UI\";\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;\n"
"background-color: rgb(240, 240, 240);\n"
"padding: 2px\n"
"\n"
"\n"
"}\n"
"\n"
"QTableWidget{\n"
"background-color: rgb(247, 247, 247);\n"
"border-bottom-left-radius: 25px;\n"
"border-bottom-right-radius: 25px;\n"
"border-left: 5px transparent\n"
"} ")
        self.TabelaBuscar.setObjectName("TabelaBuscar")
        self.TabelaBuscar.setColumnCount(6)
        self.TabelaBuscar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaBuscar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaBuscar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaBuscar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaBuscar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaBuscar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabelaBuscar.setHorizontalHeaderItem(5, item)
        self.InputBuscarB = QtWidgets.QLineEdit(self.Search1)
        self.InputBuscarB.setGeometry(QtCore.QRect(250, 40, 251, 50))
        self.InputBuscarB.setMinimumSize(QtCore.QSize(190, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.InputBuscarB.setFont(font)
        self.InputBuscarB.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.InputBuscarB.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(210, 210, 210);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(150, 150, 150);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(51, 66, 87);\n"
"color: rgb(51, 66, 87);\n"
"}")
        self.InputBuscarB.setMaxLength(100)
        self.InputBuscarB.setObjectName("InputBuscarB")
        self.BuscarButtonB = QtWidgets.QPushButton(self.Search1)
        self.BuscarButtonB.setGeometry(QtCore.QRect(180, 35, 58, 58))
        self.BuscarButtonB.setMaximumSize(QtCore.QSize(64, 64))
        self.BuscarButtonB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BuscarButtonB.setStyleSheet("background: transparent;")
        self.BuscarButtonB.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/buscariconeTOPBS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BuscarButtonB.setIcon(icon5)
        self.BuscarButtonB.setIconSize(QtCore.QSize(64, 64))
        self.BuscarButtonB.setObjectName("BuscarButtonB")
        self.VoltarButtonB = QtWidgets.QPushButton(self.Search1)
        self.VoltarButtonB.setGeometry(QtCore.QRect(550, 43, 48, 48))
        self.VoltarButtonB.setMaximumSize(QtCore.QSize(48, 48))
        self.VoltarButtonB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VoltarButtonB.setStyleSheet("background: transparent;")
        self.VoltarButtonB.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/kindpng_116879.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VoltarButtonB.setIcon(icon6)
        self.VoltarButtonB.setIconSize(QtCore.QSize(48, 48))
        self.VoltarButtonB.setObjectName("VoltarButtonB")
        self.pages.addWidget(self.Search1)
        self.Delete1 = QtWidgets.QWidget()
        self.Delete1.setObjectName("Delete1")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Delete1)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(250, 40, 251, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.ConjuntoDEL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.ConjuntoDEL.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ConjuntoDEL.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoDEL.setSpacing(8)
        self.ConjuntoDEL.setObjectName("ConjuntoDEL")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoDEL.addItem(spacerItem6)
        self.IconTopDEL_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.IconTopDEL_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        self.IconTopDEL_2.setFont(font)
        self.IconTopDEL_2.setText("")
        self.IconTopDEL_2.setPixmap(QtGui.QPixmap(":/Icons/deleteicon4.png"))
        self.IconTopDEL_2.setScaledContents(True)
        self.IconTopDEL_2.setObjectName("IconTopDEL_2")
        self.ConjuntoDEL.addWidget(self.IconTopDEL_2)
        self.text_TopDEL_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.text_TopDEL_2.setMaximumSize(QtCore.QSize(220, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_TopDEL_2.setFont(font)
        self.text_TopDEL_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.text_TopDEL_2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_TopDEL_2.setObjectName("text_TopDEL_2")
        self.ConjuntoDEL.addWidget(self.text_TopDEL_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoDEL.addItem(spacerItem7)
        self.BlueBar_6 = QtWidgets.QWidget(self.Delete1)
        self.BlueBar_6.setGeometry(QtCore.QRect(250, 100, 250, 5))
        self.BlueBar_6.setStyleSheet("background-color: rgb(60, 76, 97);\n"
"\n"
"")
        self.BlueBar_6.setObjectName("BlueBar_6")
        self.DelButtonDEL = QtWidgets.QPushButton(self.Delete1)
        self.DelButtonDEL.setGeometry(QtCore.QRect(480, 300, 240, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.DelButtonDEL.setFont(font)
        self.DelButtonDEL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DelButtonDEL.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(10, 10, 10);\n"
"border: 2px solid rgb(210, 210, 210);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(250, 250, 250);\n"
"color: rgb(10, 10, 10);\n"
"border: 2px solid rgb(160, 160, 160);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #ff0d51;\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 20px;\n"
"}")
        self.DelButtonDEL.setObjectName("DelButtonDEL")
        self.UserIconDEL = QtWidgets.QPushButton(self.Delete1)
        self.UserIconDEL.setGeometry(QtCore.QRect(40, 300, 55, 55))
        self.UserIconDEL.setMaximumSize(QtCore.QSize(55, 55))
        self.UserIconDEL.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.UserIconDEL.setStyleSheet("background: transparent;")
        self.UserIconDEL.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/free-user-icon-3296-thumb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UserIconDEL.setIcon(icon7)
        self.UserIconDEL.setIconSize(QtCore.QSize(55, 55))
        self.UserIconDEL.setObjectName("UserIconDEL")
        self.InputButtonDEL = QtWidgets.QLineEdit(self.Delete1)
        self.InputButtonDEL.setGeometry(QtCore.QRect(110, 305, 251, 50))
        self.InputButtonDEL.setMinimumSize(QtCore.QSize(190, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.InputButtonDEL.setFont(font)
        self.InputButtonDEL.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.InputButtonDEL.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(210, 210, 210);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(150, 150, 150);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(51, 66, 87);\n"
"color: rgb(51, 66, 87);\n"
"}")
        self.InputButtonDEL.setMaxLength(100)
        self.InputButtonDEL.setObjectName("InputButtonDEL")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Delete1)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(270, 140, 361, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.ConjuntoTextoAD_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.ConjuntoTextoAD_2.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoTextoAD_2.setObjectName("ConjuntoTextoAD_2")
        self.text1DEL_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text1DEL_2.setFont(font)
        self.text1DEL_2.setStyleSheet("text-align: center;")
        self.text1DEL_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text1DEL_2.setObjectName("text1DEL_2")
        self.ConjuntoTextoAD_2.addWidget(self.text1DEL_2)
        self.text2DEL_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text2DEL_2.setFont(font)
        self.text2DEL_2.setStyleSheet("text-align: center;\n"
"")
        self.text2DEL_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text2DEL_2.setObjectName("text2DEL_2")
        self.ConjuntoTextoAD_2.addWidget(self.text2DEL_2)
        self.text3DEL_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text3DEL_2.setFont(font)
        self.text3DEL_2.setStyleSheet("QLabel{\n"
"text-align: center\n"
"}")
        self.text3DEL_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text3DEL_2.setObjectName("text3DEL_2")
        self.ConjuntoTextoAD_2.addWidget(self.text3DEL_2)
        self.BSD_6 = QtWidgets.QFrame(self.Delete1)
        self.BSD_6.setGeometry(QtCore.QRect(250, 140, 5, 110))
        self.BSD_6.setMaximumSize(QtCore.QSize(12, 16777215))
        self.BSD_6.setStyleSheet("background-color: rgb(51, 66, 87);")
        self.BSD_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BSD_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BSD_6.setObjectName("BSD_6")
        self.UserDelIconDEL = QtWidgets.QPushButton(self.Delete1)
        self.UserDelIconDEL.setGeometry(QtCore.QRect(410, 300, 55, 55))
        self.UserDelIconDEL.setMaximumSize(QtCore.QSize(64, 64))
        self.UserDelIconDEL.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.UserDelIconDEL.setStyleSheet("background: transparent;")
        self.UserDelIconDEL.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/delete-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UserDelIconDEL.setIcon(icon8)
        self.UserDelIconDEL.setIconSize(QtCore.QSize(55, 55))
        self.UserDelIconDEL.setObjectName("UserDelIconDEL")
        self.DBdelIconDEL = QtWidgets.QLabel(self.Delete1)
        self.DBdelIconDEL.setGeometry(QtCore.QRect(140, 150, 80, 80))
        self.DBdelIconDEL.setText("")
        self.DBdelIconDEL.setPixmap(QtGui.QPixmap(":/Icons/database delete icon.png"))
        self.DBdelIconDEL.setScaledContents(True)
        self.DBdelIconDEL.setObjectName("DBdelIconDEL")
        self.pages.addWidget(self.Delete1)
        self.Infos1 = QtWidgets.QWidget()
        self.Infos1.setObjectName("Infos1")
        self.GitHubQRCODE = QtWidgets.QLabel(self.Infos1)
        self.GitHubQRCODE.setGeometry(QtCore.QRect(30, 120, 180, 180))
        self.GitHubQRCODE.setText("")
        self.GitHubQRCODE.setPixmap(QtGui.QPixmap(":/Icons/qrcode.png"))
        self.GitHubQRCODE.setScaledContents(True)
        self.GitHubQRCODE.setObjectName("GitHubQRCODE")
        self.GitHubIcon = QtWidgets.QLabel(self.Infos1)
        self.GitHubIcon.setGeometry(QtCore.QRect(80, 320, 70, 70))
        self.GitHubIcon.setText("")
        self.GitHubIcon.setPixmap(QtGui.QPixmap(":/Icons/25231.png"))
        self.GitHubIcon.setScaledContents(True)
        self.GitHubIcon.setObjectName("GitHubIcon")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Infos1)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(250, 40, 251, 71))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.ConjuntoDEL_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.ConjuntoDEL_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ConjuntoDEL_2.setContentsMargins(0, 0, 0, 0)
        self.ConjuntoDEL_2.setSpacing(8)
        self.ConjuntoDEL_2.setObjectName("ConjuntoDEL_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoDEL_2.addItem(spacerItem8)
        self.IconTopInfo_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.IconTopInfo_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        self.IconTopInfo_3.setFont(font)
        self.IconTopInfo_3.setText("")
        self.IconTopInfo_3.setPixmap(QtGui.QPixmap(":/Icons/infoicon.png"))
        self.IconTopInfo_3.setScaledContents(True)
        self.IconTopInfo_3.setObjectName("IconTopInfo_3")
        self.ConjuntoDEL_2.addWidget(self.IconTopInfo_3)
        self.text_TopInfo_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.text_TopInfo_3.setMaximumSize(QtCore.QSize(220, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.text_TopInfo_3.setFont(font)
        self.text_TopInfo_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.text_TopInfo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.text_TopInfo_3.setObjectName("text_TopInfo_3")
        self.ConjuntoDEL_2.addWidget(self.text_TopInfo_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ConjuntoDEL_2.addItem(spacerItem9)
        self.BlueBar_7 = QtWidgets.QWidget(self.Infos1)
        self.BlueBar_7.setGeometry(QtCore.QRect(250, 100, 250, 5))
        self.BlueBar_7.setStyleSheet("background-color: rgb(60, 76, 97);\n"
"\n"
"")
        self.BlueBar_7.setObjectName("BlueBar_7")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.Infos1)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(260, 130, 491, 241))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Texto1Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto1Info.setFont(font)
        self.Texto1Info.setObjectName("Texto1Info")
        self.verticalLayout.addWidget(self.Texto1Info)
        self.Texto2Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto2Info.setFont(font)
        self.Texto2Info.setObjectName("Texto2Info")
        self.verticalLayout.addWidget(self.Texto2Info)
        self.Texto3Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto3Info.setFont(font)
        self.Texto3Info.setObjectName("Texto3Info")
        self.verticalLayout.addWidget(self.Texto3Info)
        self.Texto4Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto4Info.setFont(font)
        self.Texto4Info.setObjectName("Texto4Info")
        self.verticalLayout.addWidget(self.Texto4Info)
        self.Texto5Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto5Info.setFont(font)
        self.Texto5Info.setObjectName("Texto5Info")
        self.verticalLayout.addWidget(self.Texto5Info)
        self.Texto6Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto6Info.setFont(font)
        self.Texto6Info.setObjectName("Texto6Info")
        self.verticalLayout.addWidget(self.Texto6Info)
        self.Texto7Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto7Info.setFont(font)
        self.Texto7Info.setObjectName("Texto7Info")
        self.verticalLayout.addWidget(self.Texto7Info)
        self.Texto8Info = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Texto8Info.setFont(font)
        self.Texto8Info.setObjectName("Texto8Info")
        self.verticalLayout.addWidget(self.Texto8Info)
        self.BSD_7 = QtWidgets.QFrame(self.Infos1)
        self.BSD_7.setGeometry(QtCore.QRect(240, 130, 5, 240))
        self.BSD_7.setMaximumSize(QtCore.QSize(12, 16777215))
        self.BSD_7.setStyleSheet("background-color: rgb(51, 66, 87);")
        self.BSD_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BSD_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BSD_7.setObjectName("BSD_7")
        self.pages.addWidget(self.Infos1)
        self.verticalLayout_2.addWidget(self.WorkSpace_2)
        self.Botton = QtWidgets.QFrame(self.WorkSpace)
        self.Botton.setMaximumSize(QtCore.QSize(16777215, 90))
        self.Botton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 25px;\n"
"border-bottom-left-radius: 25px;")
        self.Botton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Botton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Botton.setObjectName("Botton")
        self.logo = QtWidgets.QLabel(self.Botton)
        self.logo.setGeometry(QtCore.QRect(520, 10, 260, 80))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/Icons/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.Botton)
        self.horizontalLayout_2.addWidget(self.WorkSpace)
        self.horizontalLayout.addWidget(self.TotalWhiteArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gerenciamento de armários - MLK"))
        self.AddButton.setText(_translate("MainWindow", "   Adicionar"))
        self.SearchButton.setText(_translate("MainWindow", "   Buscar"))
        self.DeleteButton.setText(_translate("MainWindow", "   Excluir"))
        self.InfoButton.setText(_translate("MainWindow", "   Sobre"))
        self.textpopup.setText(_translate("MainWindow", "Alterações realizadas com sucesso"))
        self.text_topIP.setText(_translate("MainWindow", "Página Inicial"))
        self.text1PI.setText(_translate("MainWindow", "Selecione qualquer operação no menu lateral"))
        self.text2PI.setText(_translate("MainWindow", "para gerenciar os cadastros. Os dados inseridos"))
        self.text3PI.setText(_translate("MainWindow", "e/ou alterados com sucesso serão também"))
        self.text4PI.setText(_translate("MainWindow", "adicionandos a uma planilha externa .xlsx"))
        self.text_TopAd.setText(_translate("MainWindow", "Adicionar"))
        self.text1Ad.setText(_translate("MainWindow", "Preencha todos os campos ao lado para realizar um"))
        self.text2Ad.setText(_translate("MainWindow", "novo cadastro. Caso haja necessidade de alteração"))
        self.text3Ad.setText(_translate("MainWindow", "dos dados, basta sobrescrever os já existentes."))
        self.InputNomeAlunoAD.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.InputCursoAD.setPlaceholderText(_translate("MainWindow", "Curso"))
        self.InputArmarioAD.setPlaceholderText(_translate("MainWindow", "Armário (ex: A1 - 2)"))
        self.RegistrarBttn.setText(_translate("MainWindow", "ADICIONAR"))
        item = self.TabelaBuscar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Armário"))
        item = self.TabelaBuscar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Local"))
        item = self.TabelaBuscar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nome do Aluno"))
        item = self.TabelaBuscar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Curso"))
        item = self.TabelaBuscar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Data de Reserva"))
        item = self.TabelaBuscar.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Data Fim"))
        self.InputBuscarB.setPlaceholderText(_translate("MainWindow", "Buscar"))
        self.text_TopDEL_2.setText(_translate("MainWindow", "Excluir"))
        self.DelButtonDEL.setText(_translate("MainWindow", "EXCLUIR"))
        self.InputButtonDEL.setPlaceholderText(_translate("MainWindow", "Nome do Aluno"))
        self.text1DEL_2.setText(_translate("MainWindow", "Insira o nome do aluno do qual o registro"))
        self.text2DEL_2.setText(_translate("MainWindow", "deverá ser excluido, certifique-se da"))
        self.text3DEL_2.setText(_translate("MainWindow", "correta grafia."))
        self.text_TopInfo_3.setText(_translate("MainWindow", "Informações"))
        self.Texto1Info.setText(_translate("MainWindow", "Proposta de software para melhoria do sistema de "))
        self.Texto2Info.setText(_translate("MainWindow", "gerenciamento de cadastros da Etec MLK. Projeto  desenvolvido"))
        self.Texto3Info.setText(_translate("MainWindow", "para apresetação na semana tecnológica de 2022. Integrantes:"))
        self.Texto4Info.setText(_translate("MainWindow", "Emerson Amorim Marques;"))
        self.Texto5Info.setText(_translate("MainWindow", "Guilherme França Carvalho;"))
        self.Texto6Info.setText(_translate("MainWindow", "João Vitor de Oliveira;"))
        self.Texto7Info.setText(_translate("MainWindow", "Rafael Funier de Vasconcelos;"))
        self.Texto8Info.setText(_translate("MainWindow", "Raul Brasil de Sousa."))
        
        self.popup.hide()

    def error_popup(self):
        self.popup.setStyleSheet("background-color: #ff0d51;\n"
"border-radius: 11px;")
    def sucess_popup(self):
        self.popup.setStyleSheet("background-color: #0DDF90;\n"
"border-radius: 11px;")
    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
